"""add week and task

Revision ID: 44a7a5ae9877
Revises: 70a29c5e4aaa
Create Date: 2026-05-30 19:48:41.524348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a7a5ae9877'
down_revision: Union[str, None] = '70a29c5e4aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('plaud_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('plaud', 'manual', 'decomposed', name='tasksource', native_enum=False, length=16), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'in_progress', 'stuck', 'decomposed', name='taskstatus', native_enum=False, length=16), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dialog_state', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_dialog_state_active_week_id_week',
            'week',
            ['active_week_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialog_state', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_dialog_state_active_week_id_week', type_='foreignkey'
        )

    op.drop_table('task')
    op.drop_table('week')
    # ### end Alembic commands ###
