"""add dialog_state

Revision ID: 70a29c5e4aaa
Revises: 6bbb07522e37
Create Date: 2026-05-30 19:42:03.081238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a29c5e4aaa'
down_revision: Union[str, None] = '6bbb07522e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_state',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('idle', 'confirming_tasks', 'checkin', 'decomposing', name='dialogstateenum', native_enum=False, length=32), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('active_week_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialog_state')
    # ### end Alembic commands ###
